import './globals.css'
import { Kanit } from 'next/font/google'

const kanit = Kanit(
  {
      weight: '400',
     subsets: ['latin'] 
    }
  )

export const metadata = {
  title: 'Zleads',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={kanit.className}>{children}</body>
    </html>
  )
}
