version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - npm install
      - ls
      - npm run build
      - ls
      - cd out
      - ls
      - aws s3 rm s3://bucket-f03bf761-master --recursive
      - aws s3 sync . s3://bucket-f03bf761-master
